codota/tabnine-nvim

- doc/tabnine.txt
Adds doc/tabnine.txt for in application help and documentation using nvim. Allows for `:help tabnine` to show help from inside NeoVim.
- Further commands can be added in later commits when added (ie #54)
- The convention is to include the license type in the help menu (see [rstacruz/cheatsheets](https://github.com/rstacruz/cheatsheets/blob/master/vim-help.md#Author-lines), [vim-prettier](https://github.com/prettier/vim-prettier/blob/master/doc/prettier.txt#L10), and [suda.vim](https://github.com/lambdalisue/suda.vim/blob/master/doc/suda.txt#L4) for examples), however I was unable to find what license this project is under. I would highly suggest adding a `LICENSE.txt` to the repo for clarification on these such issues.
> [Feature] Add vim documentation

- .gitignore
This is autogenerated by Neovim, so should be added to the ignore file
> add docs/tags to .gitignore

- lua/tabnine/binary.lua
- lua/tabnine/user_commands.lua
This option interferes with certain other plugins (especially LSPs) which expect an empty table to be encoded as an array. This is not being used in our current implementation, and can be removed without any other changes to the code.
Documentation on this option: https://github.com/Kong/kong-cjson#encode_empty_table_as_object
See my comment on #65 determining [lack of] use case: https://github.com/codota/tabnine-nvim/issues/65#issuecomment-1516530047
Note: Special consideration should be taken in the future to avoid passing empty tables to `json.encode()` when an object is expected, rather than a table. Dummy values can be attached to the table if necessary, to ensure that it's not considered empty. Ex:
```lua
local empty_table = {}
-- either:
empty_table.dummy=true …
```
> Remove `json.encode_empty_table_as_object(true)`

- dl_binaries.ps1
- dl_binaries.sh
Modifies `dl_binaries.sh` to automatically detect the current infrastructure and only install the necessary binaries, as well as allowing positional arguments to force installation of specific binaries.
Also allows environment variable `version` to be set and override the version to download.
I don't know *any* powershell, so someone else will have to make the modifications necessary to `dl_binaries.ps1`.
Fixes #52.
> [Feature] Avoid download of *all* binaries on install.

- lua/tabnine.lua
- lua/tabnine/consts.lua
This patch checks the neovim version early to ensure it's greater than our minimum supported version (0.7.1) and sends a warning (once) on setup if it's not.
> Notify the user if the nvim version is too low to use tabnine-nvim

- .gitmodules
- examples/javascript.js
- lua/tabnine/binary.lua
- switch to vim version
- switch to vim version
> vim version

- dl_binaries.sh
- fix quoting of custom update service URL
- This was introduced in introduction of enterprise support
- make both curl commands follow redirects
- add fail to version curl command for consistency
- This makes both `curl` commands have the same arguments, and also fails earlier if something is wrong with the URL
> Shell script fixes

- dl_binaries.ps1
This fixes #76. I used `-ne` as opposed to `-gt` for slightly more robustness, as LastExitCode is permitted (on windows) to contain negative integers.
> Fix: check for failure, not success of request in `dl_binaries.ps1`

- dl_binaries.ps1
This adds support for defining the version to install with `$Env:version`, as well as using the first argument as the update URL.
> Make the powershell script symetric to the shell script

- .gitmodules
- lua/tabnine.lua
- lua/tabnine/binary.lua
Neovim v0.9.0 added `lua-version` under the `vim.version` umbrella, however before 0.9.0, `vim.version` is just a regular function that returns the neovim version without any other features.
This patch reintroduces the `semver` dependency (reverting #80), and uses `semver` to check the version compatibility in `lua/tabnine.lua`
Fixes #85
> Fix `vim.version`

- lua/tabnine/auto_commands.lua
This should fix #74 by clearing completions on any cursor movement outside of insert mode.
This is only triggered in normal and visual modes according to the docs
> clear completions on CursorMoved

- lua/tabnine/chat/init.lua
- lua/tabnine/utils.lua
This commit fixes a bug, when creating a visual selection which was inverted would cause an error while getting the current selection.
To reproduce the original bug: `10jV5k` in nvim then `/explain-code` in the tabnine window.
> fix(chat): fix inverted visual selection

- lua/tabnine/chat/init.lua
this print was erroniously added in 012925ae30cdc6f322616dce0311c8b7460ff643
This print statement was likely added while debugging the diagnostics implementation, but was forgotten.
This commit just removes it to ensure minimal disruption to user workflow.
> Remove debug print statment added in 012925ae

- lua/tabnine/chat/binary.lua
Or if it exits with a non-zero exit code.
If :TabnineChat gets run in a tty, this will result in exiting with a code of 1, previously silently failing. This change will at least let the user know *something* went wrong.
> Warn the user if the chat binary failed to start

- .editorconfig
This file can be read by many editors (vscode, [n]vim, etc) to ensure consistent styling without additional thought.
> Add an .editorconfig to ensure formatting

- lua/tabnine/completion.lua
I found tabnine-nvim often does not give any result. This fixes the problem.
> Fix a bug when #response.results == 1

- dl_binaries.ps1
Fixes #121
Note: I believe this was introduced *after* windows 7. I’m not certain though because Microsoft’s documentation seems to believe old versions won’t matter to anyone 🙄
> Change arch check in dl-binaries.ps1

- lua/tabnine/binary.lua
- lua/tabnine/chat/binary.lua
- lua/tabnine/chat/init.lua
- lua/tabnine/status.lua
- use luanil argument in vim.json.decode
This ensures that `null` will be decoded as `nil` instead of `vim.NIL`(a userdata object).
This allows nicer error messages and easier reasoning (ie, `if val then ...`)
- check for response before indexing it
If it's not available, set service_level to 'unknown' to avoid displaying 'loading'.
fixes #119. fixes #120.
> fix: vim.NIL index error in status.lua

- lua/tabnine/chat/codelens.lua
fixes #140. this is untested, but according to the docs should work. Please test this (or wait until I can) before merging!
> DEV2-4801 fix: remove deprecated use of vim.lsp.buf.server_ready

- lua/tabnine/completion.lua
fix #155 and #158 due to the different behaviour of `nvim_buf_set_text` api between v0.10 and v0.9 https://github.com/codota/tabnine-nvim/issues/155#issuecomment-2000057812
> fix: wrong cursor position after completion due to nvim version

- lua/tabnine/binary.lua
- lua/tabnine/chat/binary.lua
- lua/tabnine/chat/init.lua
- lua/tabnine/status.lua
- lua/tabnine/utils.lua
part 3 of #141
This more clearly describes what it returns.
script_path is replaced with script_dir which returns a value based on the currently running file
note: module_dir relies on utils.lua's location, and will break if the file is moved
> refactor!: remove utils.script_path and replace with utils.module_dir

- lua/tabnine/utils.lua
part 2 of #141
Remove the (accidental?) global in selection_range and pass as a parameter instead
> fix: remove global `selection_mode` in `select_range`

- README.md
- doc/tabnine.txt
- lua/tabnine/completion.lua
- lua/tabnine/keymaps.lua
This PR implements `accept_suggestion`, `dismiss_suggestion`, and `has_suggestion` to be used from user mappings.
It also permits setting `accept_keymap` and `dismiss_keymap` to `false` to avoid setting it (`nil` defaults to the default settings)
fixes #149 
I've included an example use case under a new header in the README.
copied from the readme:
```lua
--- Example integration with Tabnine and LuaSnip; falling back to inserting tab if neither has a completion
vim.keymap.set("i", "<tab>", function()
if require("tabnine.keymaps").has_suggestion() then
return require("tabnine.keymaps").accept_suggestion()
elseif require("luasnip").jumpable(1) then
return require("luasnip").jump(1)
else
return "<tab>"
end
end, { expr = true })
```
> Refactor(keymaps): export keymaps

- README.md
- lua/tabnine/binary.lua
- lua/tabnine/chat/binary.lua
- lua/tabnine/chat/codelens.lua
- lua/tabnine/chat/init.lua
- lua/tabnine/completion.lua
- lua/tabnine/state.lua
- lua/tabnine/status.lua
- lua/tabnine/utils.lua
- lua/tabnine/workspace.lua
This fixes several deprecation warnings in nvim 0.10.
It should still work in previous versions.
- **fix: vim.lsp.buf_get_clients is deprecated**
- **fix: vim.loop is deprecated**
- **fix: vim.api.nvim_buf_get_option is deprecated**
> Fix deprecation warnings in nvim 0.10

- .github/workflows/lua-format-check-pr.yml
- .styluaignore
- lua/tabnine/binary.lua
This commit adds a step to the lua-format-check-pr job that will leave a
comment with "suggested changes" when formatting needs to be applied.
This can then be applied with one click (per file).
Alternatively, I could change it to automattically add a commit that
formats the code. Several PRs have gotten through without proper
formatting, which makes all future PRs fail the checks.
> chore: add comments on pr suggesting formatting
